apiVersion: v1
kind: Service
metadata:
  name: {{ .Value.Name }}
  labels:
    app: {{ .Value.Name }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Value.Name }}
