## This is basic continuous integration build for your Quarkus application.

name: build and push image

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Verify
        run: ./mvnw verify -B

      - name: Maven Package
        run: ./mvnw package -Pnative

      - name: Build Docker Image
        run:  docker build -f src/main/docker/Dockerfile.native -t quarkus/bar .

      - name: Setup IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "eu-west-1"
          role-to-assume: ${{ secrets.ecr_accessor_role_arn }}

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: all

      - name: Push to ECR
        shell: bash
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.aws_account }}.dkr.ecr.eu-west-1.amazonaws.com
          docker push ${{ secrets.aws_account }}.dkr.ecr.${{ matrix.region }}.amazonaws.com/simple-server:${{ env.PR_NUMBER }}-${{ github.head_ref }}
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}